// Code generated by go-swagger; DO NOT EDIT.

package bgp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateBGPSessionParams creates a new UpdateBGPSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateBGPSessionParams() *UpdateBGPSessionParams {
	return &UpdateBGPSessionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateBGPSessionParamsWithTimeout creates a new UpdateBGPSessionParams object
// with the ability to set a timeout on a request.
func NewUpdateBGPSessionParamsWithTimeout(timeout time.Duration) *UpdateBGPSessionParams {
	return &UpdateBGPSessionParams{
		timeout: timeout,
	}
}

// NewUpdateBGPSessionParamsWithContext creates a new UpdateBGPSessionParams object
// with the ability to set a context for a request.
func NewUpdateBGPSessionParamsWithContext(ctx context.Context) *UpdateBGPSessionParams {
	return &UpdateBGPSessionParams{
		Context: ctx,
	}
}

// NewUpdateBGPSessionParamsWithHTTPClient creates a new UpdateBGPSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateBGPSessionParamsWithHTTPClient(client *http.Client) *UpdateBGPSessionParams {
	return &UpdateBGPSessionParams{
		HTTPClient: client,
	}
}

/* UpdateBGPSessionParams contains all the parameters to send to the API endpoint
   for the update Bgp session operation.

   Typically these are written to a http.Request.
*/
type UpdateBGPSessionParams struct {

	/* DefaultRoute.

	   Default route
	*/
	DefaultRoute bool

	/* ID.

	   BGP session UUID

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update Bgp session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBGPSessionParams) WithDefaults() *UpdateBGPSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update Bgp session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBGPSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update Bgp session params
func (o *UpdateBGPSessionParams) WithTimeout(timeout time.Duration) *UpdateBGPSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update Bgp session params
func (o *UpdateBGPSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update Bgp session params
func (o *UpdateBGPSessionParams) WithContext(ctx context.Context) *UpdateBGPSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update Bgp session params
func (o *UpdateBGPSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update Bgp session params
func (o *UpdateBGPSessionParams) WithHTTPClient(client *http.Client) *UpdateBGPSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update Bgp session params
func (o *UpdateBGPSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDefaultRoute adds the defaultRoute to the update Bgp session params
func (o *UpdateBGPSessionParams) WithDefaultRoute(defaultRoute bool) *UpdateBGPSessionParams {
	o.SetDefaultRoute(defaultRoute)
	return o
}

// SetDefaultRoute adds the defaultRoute to the update Bgp session params
func (o *UpdateBGPSessionParams) SetDefaultRoute(defaultRoute bool) {
	o.DefaultRoute = defaultRoute
}

// WithID adds the id to the update Bgp session params
func (o *UpdateBGPSessionParams) WithID(id strfmt.UUID) *UpdateBGPSessionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update Bgp session params
func (o *UpdateBGPSessionParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateBGPSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.DefaultRoute); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
