// Code generated by go-swagger; DO NOT EDIT.

package b_g_p

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteBgpSessionReader is a Reader for the DeleteBgpSession structure.
type DeleteBgpSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBgpSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteBgpSessionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteBgpSessionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteBgpSessionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteBgpSessionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteBgpSessionNoContent creates a DeleteBgpSessionNoContent with default headers values
func NewDeleteBgpSessionNoContent() *DeleteBgpSessionNoContent {
	return &DeleteBgpSessionNoContent{}
}

/*DeleteBgpSessionNoContent handles this case with default header values.

no content
*/
type DeleteBgpSessionNoContent struct {
}

func (o *DeleteBgpSessionNoContent) Error() string {
	return fmt.Sprintf("[DELETE /bgp/sessions/{id}][%d] deleteBgpSessionNoContent ", 204)
}

func (o *DeleteBgpSessionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteBgpSessionUnauthorized creates a DeleteBgpSessionUnauthorized with default headers values
func NewDeleteBgpSessionUnauthorized() *DeleteBgpSessionUnauthorized {
	return &DeleteBgpSessionUnauthorized{}
}

/*DeleteBgpSessionUnauthorized handles this case with default header values.

unauthorized
*/
type DeleteBgpSessionUnauthorized struct {
}

func (o *DeleteBgpSessionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /bgp/sessions/{id}][%d] deleteBgpSessionUnauthorized ", 401)
}

func (o *DeleteBgpSessionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteBgpSessionForbidden creates a DeleteBgpSessionForbidden with default headers values
func NewDeleteBgpSessionForbidden() *DeleteBgpSessionForbidden {
	return &DeleteBgpSessionForbidden{}
}

/*DeleteBgpSessionForbidden handles this case with default header values.

forbidden
*/
type DeleteBgpSessionForbidden struct {
}

func (o *DeleteBgpSessionForbidden) Error() string {
	return fmt.Sprintf("[DELETE /bgp/sessions/{id}][%d] deleteBgpSessionForbidden ", 403)
}

func (o *DeleteBgpSessionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteBgpSessionNotFound creates a DeleteBgpSessionNotFound with default headers values
func NewDeleteBgpSessionNotFound() *DeleteBgpSessionNotFound {
	return &DeleteBgpSessionNotFound{}
}

/*DeleteBgpSessionNotFound handles this case with default header values.

not found
*/
type DeleteBgpSessionNotFound struct {
}

func (o *DeleteBgpSessionNotFound) Error() string {
	return fmt.Sprintf("[DELETE /bgp/sessions/{id}][%d] deleteBgpSessionNotFound ", 404)
}

func (o *DeleteBgpSessionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
