// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindBgpConfigByProjectParams creates a new FindBgpConfigByProjectParams object
// with the default values initialized.
func NewFindBgpConfigByProjectParams() *FindBgpConfigByProjectParams {
	var ()
	return &FindBgpConfigByProjectParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindBgpConfigByProjectParamsWithTimeout creates a new FindBgpConfigByProjectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindBgpConfigByProjectParamsWithTimeout(timeout time.Duration) *FindBgpConfigByProjectParams {
	var ()
	return &FindBgpConfigByProjectParams{

		timeout: timeout,
	}
}

// NewFindBgpConfigByProjectParamsWithContext creates a new FindBgpConfigByProjectParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindBgpConfigByProjectParamsWithContext(ctx context.Context) *FindBgpConfigByProjectParams {
	var ()
	return &FindBgpConfigByProjectParams{

		Context: ctx,
	}
}

// NewFindBgpConfigByProjectParamsWithHTTPClient creates a new FindBgpConfigByProjectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindBgpConfigByProjectParamsWithHTTPClient(client *http.Client) *FindBgpConfigByProjectParams {
	var ()
	return &FindBgpConfigByProjectParams{
		HTTPClient: client,
	}
}

/*FindBgpConfigByProjectParams contains all the parameters to send to the API endpoint
for the find bgp config by project operation typically these are written to a http.Request
*/
type FindBgpConfigByProjectParams struct {

	/*ID
	  Project UUID

	*/
	ID strfmt.UUID
	/*Include
	  related attributes to include

	*/
	Include *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) WithTimeout(timeout time.Duration) *FindBgpConfigByProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) WithContext(ctx context.Context) *FindBgpConfigByProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) WithHTTPClient(client *http.Client) *FindBgpConfigByProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) WithID(id strfmt.UUID) *FindBgpConfigByProjectParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithInclude adds the include to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) WithInclude(include *string) *FindBgpConfigByProjectParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the find bgp config by project params
func (o *FindBgpConfigByProjectParams) SetInclude(include *string) {
	o.Include = include
}

// WriteToRequest writes these params to a swagger request
func (o *FindBgpConfigByProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if o.Include != nil {

		// query param include
		var qrInclude string
		if o.Include != nil {
			qrInclude = *o.Include
		}
		qInclude := qrInclude
		if qInclude != "" {
			if err := r.SetQueryParam("include", qInclude); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
