// Code generated by go-swagger; DO NOT EDIT.

package connections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProjectListInterconnectionsParams creates a new ProjectListInterconnectionsParams object
// with the default values initialized.
func NewProjectListInterconnectionsParams() *ProjectListInterconnectionsParams {
	var ()
	return &ProjectListInterconnectionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectListInterconnectionsParamsWithTimeout creates a new ProjectListInterconnectionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectListInterconnectionsParamsWithTimeout(timeout time.Duration) *ProjectListInterconnectionsParams {
	var ()
	return &ProjectListInterconnectionsParams{

		timeout: timeout,
	}
}

// NewProjectListInterconnectionsParamsWithContext creates a new ProjectListInterconnectionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectListInterconnectionsParamsWithContext(ctx context.Context) *ProjectListInterconnectionsParams {
	var ()
	return &ProjectListInterconnectionsParams{

		Context: ctx,
	}
}

// NewProjectListInterconnectionsParamsWithHTTPClient creates a new ProjectListInterconnectionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectListInterconnectionsParamsWithHTTPClient(client *http.Client) *ProjectListInterconnectionsParams {
	var ()
	return &ProjectListInterconnectionsParams{
		HTTPClient: client,
	}
}

/*ProjectListInterconnectionsParams contains all the parameters to send to the API endpoint
for the project list interconnections operation typically these are written to a http.Request
*/
type ProjectListInterconnectionsParams struct {

	/*ProjectID
	  UUID of the project

	*/
	ProjectID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the project list interconnections params
func (o *ProjectListInterconnectionsParams) WithTimeout(timeout time.Duration) *ProjectListInterconnectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the project list interconnections params
func (o *ProjectListInterconnectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the project list interconnections params
func (o *ProjectListInterconnectionsParams) WithContext(ctx context.Context) *ProjectListInterconnectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the project list interconnections params
func (o *ProjectListInterconnectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the project list interconnections params
func (o *ProjectListInterconnectionsParams) WithHTTPClient(client *http.Client) *ProjectListInterconnectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the project list interconnections params
func (o *ProjectListInterconnectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectID adds the projectID to the project list interconnections params
func (o *ProjectListInterconnectionsParams) WithProjectID(projectID strfmt.UUID) *ProjectListInterconnectionsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the project list interconnections params
func (o *ProjectListInterconnectionsParams) SetProjectID(projectID strfmt.UUID) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectListInterconnectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
