/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
)

// MoveHardwareReservation201ResponseProject struct for MoveHardwareReservation201ResponseProject
type MoveHardwareReservation201ResponseProject struct {
	BgpConfig     *FindBatchById200ResponseDevicesInner  `json:"bgp_config,omitempty"`
	CreatedAt     *time.Time                             `json:"created_at,omitempty"`
	Customdata    map[string]interface{}                 `json:"customdata,omitempty"`
	Devices       []FindBatchById200ResponseDevicesInner `json:"devices,omitempty"`
	Id            *string                                `json:"id,omitempty"`
	Invitations   []FindBatchById200ResponseDevicesInner `json:"invitations,omitempty"`
	MaxDevices    map[string]interface{}                 `json:"max_devices,omitempty"`
	Members       []FindBatchById200ResponseDevicesInner `json:"members,omitempty"`
	Memberships   []FindBatchById200ResponseDevicesInner `json:"memberships,omitempty"`
	Name          *string                                `json:"name,omitempty"`
	NetworkStatus map[string]interface{}                 `json:"network_status,omitempty"`
	PaymentMethod *FindBatchById200ResponseDevicesInner  `json:"payment_method,omitempty"`
	SshKeys       []FindBatchById200ResponseDevicesInner `json:"ssh_keys,omitempty"`
	UpdatedAt     *time.Time                             `json:"updated_at,omitempty"`
	Volumes       []FindBatchById200ResponseDevicesInner `json:"volumes,omitempty"`
}

// NewMoveHardwareReservation201ResponseProject instantiates a new MoveHardwareReservation201ResponseProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoveHardwareReservation201ResponseProject() *MoveHardwareReservation201ResponseProject {
	this := MoveHardwareReservation201ResponseProject{}
	return &this
}

// NewMoveHardwareReservation201ResponseProjectWithDefaults instantiates a new MoveHardwareReservation201ResponseProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoveHardwareReservation201ResponseProjectWithDefaults() *MoveHardwareReservation201ResponseProject {
	this := MoveHardwareReservation201ResponseProject{}
	return &this
}

// GetBgpConfig returns the BgpConfig field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetBgpConfig() FindBatchById200ResponseDevicesInner {
	if o == nil || o.BgpConfig == nil {
		var ret FindBatchById200ResponseDevicesInner
		return ret
	}
	return *o.BgpConfig
}

// GetBgpConfigOk returns a tuple with the BgpConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetBgpConfigOk() (*FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.BgpConfig == nil {
		return nil, false
	}
	return o.BgpConfig, true
}

// HasBgpConfig returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasBgpConfig() bool {
	if o != nil && o.BgpConfig != nil {
		return true
	}

	return false
}

// SetBgpConfig gets a reference to the given FindBatchById200ResponseDevicesInner and assigns it to the BgpConfig field.
func (o *MoveHardwareReservation201ResponseProject) SetBgpConfig(v FindBatchById200ResponseDevicesInner) {
	o.BgpConfig = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *MoveHardwareReservation201ResponseProject) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCustomdata returns the Customdata field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetCustomdata() map[string]interface{} {
	if o == nil || o.Customdata == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Customdata
}

// GetCustomdataOk returns a tuple with the Customdata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetCustomdataOk() (map[string]interface{}, bool) {
	if o == nil || o.Customdata == nil {
		return nil, false
	}
	return o.Customdata, true
}

// HasCustomdata returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasCustomdata() bool {
	if o != nil && o.Customdata != nil {
		return true
	}

	return false
}

// SetCustomdata gets a reference to the given map[string]interface{} and assigns it to the Customdata field.
func (o *MoveHardwareReservation201ResponseProject) SetCustomdata(v map[string]interface{}) {
	o.Customdata = v
}

// GetDevices returns the Devices field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetDevices() []FindBatchById200ResponseDevicesInner {
	if o == nil || o.Devices == nil {
		var ret []FindBatchById200ResponseDevicesInner
		return ret
	}
	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetDevicesOk() ([]FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Devices == nil {
		return nil, false
	}
	return o.Devices, true
}

// HasDevices returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasDevices() bool {
	if o != nil && o.Devices != nil {
		return true
	}

	return false
}

// SetDevices gets a reference to the given []FindBatchById200ResponseDevicesInner and assigns it to the Devices field.
func (o *MoveHardwareReservation201ResponseProject) SetDevices(v []FindBatchById200ResponseDevicesInner) {
	o.Devices = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MoveHardwareReservation201ResponseProject) SetId(v string) {
	o.Id = &v
}

// GetInvitations returns the Invitations field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetInvitations() []FindBatchById200ResponseDevicesInner {
	if o == nil || o.Invitations == nil {
		var ret []FindBatchById200ResponseDevicesInner
		return ret
	}
	return o.Invitations
}

// GetInvitationsOk returns a tuple with the Invitations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetInvitationsOk() ([]FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Invitations == nil {
		return nil, false
	}
	return o.Invitations, true
}

// HasInvitations returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasInvitations() bool {
	if o != nil && o.Invitations != nil {
		return true
	}

	return false
}

// SetInvitations gets a reference to the given []FindBatchById200ResponseDevicesInner and assigns it to the Invitations field.
func (o *MoveHardwareReservation201ResponseProject) SetInvitations(v []FindBatchById200ResponseDevicesInner) {
	o.Invitations = v
}

// GetMaxDevices returns the MaxDevices field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetMaxDevices() map[string]interface{} {
	if o == nil || o.MaxDevices == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.MaxDevices
}

// GetMaxDevicesOk returns a tuple with the MaxDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetMaxDevicesOk() (map[string]interface{}, bool) {
	if o == nil || o.MaxDevices == nil {
		return nil, false
	}
	return o.MaxDevices, true
}

// HasMaxDevices returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasMaxDevices() bool {
	if o != nil && o.MaxDevices != nil {
		return true
	}

	return false
}

// SetMaxDevices gets a reference to the given map[string]interface{} and assigns it to the MaxDevices field.
func (o *MoveHardwareReservation201ResponseProject) SetMaxDevices(v map[string]interface{}) {
	o.MaxDevices = v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetMembers() []FindBatchById200ResponseDevicesInner {
	if o == nil || o.Members == nil {
		var ret []FindBatchById200ResponseDevicesInner
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetMembersOk() ([]FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Members == nil {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasMembers() bool {
	if o != nil && o.Members != nil {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []FindBatchById200ResponseDevicesInner and assigns it to the Members field.
func (o *MoveHardwareReservation201ResponseProject) SetMembers(v []FindBatchById200ResponseDevicesInner) {
	o.Members = v
}

// GetMemberships returns the Memberships field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetMemberships() []FindBatchById200ResponseDevicesInner {
	if o == nil || o.Memberships == nil {
		var ret []FindBatchById200ResponseDevicesInner
		return ret
	}
	return o.Memberships
}

// GetMembershipsOk returns a tuple with the Memberships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetMembershipsOk() ([]FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Memberships == nil {
		return nil, false
	}
	return o.Memberships, true
}

// HasMemberships returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasMemberships() bool {
	if o != nil && o.Memberships != nil {
		return true
	}

	return false
}

// SetMemberships gets a reference to the given []FindBatchById200ResponseDevicesInner and assigns it to the Memberships field.
func (o *MoveHardwareReservation201ResponseProject) SetMemberships(v []FindBatchById200ResponseDevicesInner) {
	o.Memberships = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MoveHardwareReservation201ResponseProject) SetName(v string) {
	o.Name = &v
}

// GetNetworkStatus returns the NetworkStatus field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetNetworkStatus() map[string]interface{} {
	if o == nil || o.NetworkStatus == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.NetworkStatus
}

// GetNetworkStatusOk returns a tuple with the NetworkStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetNetworkStatusOk() (map[string]interface{}, bool) {
	if o == nil || o.NetworkStatus == nil {
		return nil, false
	}
	return o.NetworkStatus, true
}

// HasNetworkStatus returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasNetworkStatus() bool {
	if o != nil && o.NetworkStatus != nil {
		return true
	}

	return false
}

// SetNetworkStatus gets a reference to the given map[string]interface{} and assigns it to the NetworkStatus field.
func (o *MoveHardwareReservation201ResponseProject) SetNetworkStatus(v map[string]interface{}) {
	o.NetworkStatus = v
}

// GetPaymentMethod returns the PaymentMethod field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetPaymentMethod() FindBatchById200ResponseDevicesInner {
	if o == nil || o.PaymentMethod == nil {
		var ret FindBatchById200ResponseDevicesInner
		return ret
	}
	return *o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetPaymentMethodOk() (*FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.PaymentMethod == nil {
		return nil, false
	}
	return o.PaymentMethod, true
}

// HasPaymentMethod returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasPaymentMethod() bool {
	if o != nil && o.PaymentMethod != nil {
		return true
	}

	return false
}

// SetPaymentMethod gets a reference to the given FindBatchById200ResponseDevicesInner and assigns it to the PaymentMethod field.
func (o *MoveHardwareReservation201ResponseProject) SetPaymentMethod(v FindBatchById200ResponseDevicesInner) {
	o.PaymentMethod = &v
}

// GetSshKeys returns the SshKeys field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetSshKeys() []FindBatchById200ResponseDevicesInner {
	if o == nil || o.SshKeys == nil {
		var ret []FindBatchById200ResponseDevicesInner
		return ret
	}
	return o.SshKeys
}

// GetSshKeysOk returns a tuple with the SshKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetSshKeysOk() ([]FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.SshKeys == nil {
		return nil, false
	}
	return o.SshKeys, true
}

// HasSshKeys returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasSshKeys() bool {
	if o != nil && o.SshKeys != nil {
		return true
	}

	return false
}

// SetSshKeys gets a reference to the given []FindBatchById200ResponseDevicesInner and assigns it to the SshKeys field.
func (o *MoveHardwareReservation201ResponseProject) SetSshKeys(v []FindBatchById200ResponseDevicesInner) {
	o.SshKeys = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *MoveHardwareReservation201ResponseProject) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetVolumes returns the Volumes field value if set, zero value otherwise.
func (o *MoveHardwareReservation201ResponseProject) GetVolumes() []FindBatchById200ResponseDevicesInner {
	if o == nil || o.Volumes == nil {
		var ret []FindBatchById200ResponseDevicesInner
		return ret
	}
	return o.Volumes
}

// GetVolumesOk returns a tuple with the Volumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoveHardwareReservation201ResponseProject) GetVolumesOk() ([]FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Volumes == nil {
		return nil, false
	}
	return o.Volumes, true
}

// HasVolumes returns a boolean if a field has been set.
func (o *MoveHardwareReservation201ResponseProject) HasVolumes() bool {
	if o != nil && o.Volumes != nil {
		return true
	}

	return false
}

// SetVolumes gets a reference to the given []FindBatchById200ResponseDevicesInner and assigns it to the Volumes field.
func (o *MoveHardwareReservation201ResponseProject) SetVolumes(v []FindBatchById200ResponseDevicesInner) {
	o.Volumes = v
}

func (o MoveHardwareReservation201ResponseProject) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BgpConfig != nil {
		toSerialize["bgp_config"] = o.BgpConfig
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Customdata != nil {
		toSerialize["customdata"] = o.Customdata
	}
	if o.Devices != nil {
		toSerialize["devices"] = o.Devices
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Invitations != nil {
		toSerialize["invitations"] = o.Invitations
	}
	if o.MaxDevices != nil {
		toSerialize["max_devices"] = o.MaxDevices
	}
	if o.Members != nil {
		toSerialize["members"] = o.Members
	}
	if o.Memberships != nil {
		toSerialize["memberships"] = o.Memberships
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.NetworkStatus != nil {
		toSerialize["network_status"] = o.NetworkStatus
	}
	if o.PaymentMethod != nil {
		toSerialize["payment_method"] = o.PaymentMethod
	}
	if o.SshKeys != nil {
		toSerialize["ssh_keys"] = o.SshKeys
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if o.Volumes != nil {
		toSerialize["volumes"] = o.Volumes
	}
	return json.Marshal(toSerialize)
}

type NullableMoveHardwareReservation201ResponseProject struct {
	value *MoveHardwareReservation201ResponseProject
	isSet bool
}

func (v NullableMoveHardwareReservation201ResponseProject) Get() *MoveHardwareReservation201ResponseProject {
	return v.value
}

func (v *NullableMoveHardwareReservation201ResponseProject) Set(val *MoveHardwareReservation201ResponseProject) {
	v.value = val
	v.isSet = true
}

func (v NullableMoveHardwareReservation201ResponseProject) IsSet() bool {
	return v.isSet
}

func (v *NullableMoveHardwareReservation201ResponseProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoveHardwareReservation201ResponseProject(val *MoveHardwareReservation201ResponseProject) *NullableMoveHardwareReservation201ResponseProject {
	return &NullableMoveHardwareReservation201ResponseProject{value: val, isSet: true}
}

func (v NullableMoveHardwareReservation201ResponseProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoveHardwareReservation201ResponseProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
