/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// CheckCapacityForFacilityRequestServersInner struct for CheckCapacityForFacilityRequestServersInner
type CheckCapacityForFacilityRequestServersInner struct {
	Facility *string `json:"facility,omitempty"`
	Plan     *string `json:"plan,omitempty"`
	Quantity *string `json:"quantity,omitempty"`
}

// NewCheckCapacityForFacilityRequestServersInner instantiates a new CheckCapacityForFacilityRequestServersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckCapacityForFacilityRequestServersInner() *CheckCapacityForFacilityRequestServersInner {
	this := CheckCapacityForFacilityRequestServersInner{}
	return &this
}

// NewCheckCapacityForFacilityRequestServersInnerWithDefaults instantiates a new CheckCapacityForFacilityRequestServersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckCapacityForFacilityRequestServersInnerWithDefaults() *CheckCapacityForFacilityRequestServersInner {
	this := CheckCapacityForFacilityRequestServersInner{}
	return &this
}

// GetFacility returns the Facility field value if set, zero value otherwise.
func (o *CheckCapacityForFacilityRequestServersInner) GetFacility() string {
	if o == nil || o.Facility == nil {
		var ret string
		return ret
	}
	return *o.Facility
}

// GetFacilityOk returns a tuple with the Facility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckCapacityForFacilityRequestServersInner) GetFacilityOk() (*string, bool) {
	if o == nil || o.Facility == nil {
		return nil, false
	}
	return o.Facility, true
}

// HasFacility returns a boolean if a field has been set.
func (o *CheckCapacityForFacilityRequestServersInner) HasFacility() bool {
	if o != nil && o.Facility != nil {
		return true
	}

	return false
}

// SetFacility gets a reference to the given string and assigns it to the Facility field.
func (o *CheckCapacityForFacilityRequestServersInner) SetFacility(v string) {
	o.Facility = &v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *CheckCapacityForFacilityRequestServersInner) GetPlan() string {
	if o == nil || o.Plan == nil {
		var ret string
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckCapacityForFacilityRequestServersInner) GetPlanOk() (*string, bool) {
	if o == nil || o.Plan == nil {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *CheckCapacityForFacilityRequestServersInner) HasPlan() bool {
	if o != nil && o.Plan != nil {
		return true
	}

	return false
}

// SetPlan gets a reference to the given string and assigns it to the Plan field.
func (o *CheckCapacityForFacilityRequestServersInner) SetPlan(v string) {
	o.Plan = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *CheckCapacityForFacilityRequestServersInner) GetQuantity() string {
	if o == nil || o.Quantity == nil {
		var ret string
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckCapacityForFacilityRequestServersInner) GetQuantityOk() (*string, bool) {
	if o == nil || o.Quantity == nil {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *CheckCapacityForFacilityRequestServersInner) HasQuantity() bool {
	if o != nil && o.Quantity != nil {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given string and assigns it to the Quantity field.
func (o *CheckCapacityForFacilityRequestServersInner) SetQuantity(v string) {
	o.Quantity = &v
}

func (o CheckCapacityForFacilityRequestServersInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Facility != nil {
		toSerialize["facility"] = o.Facility
	}
	if o.Plan != nil {
		toSerialize["plan"] = o.Plan
	}
	if o.Quantity != nil {
		toSerialize["quantity"] = o.Quantity
	}
	return json.Marshal(toSerialize)
}

type NullableCheckCapacityForFacilityRequestServersInner struct {
	value *CheckCapacityForFacilityRequestServersInner
	isSet bool
}

func (v NullableCheckCapacityForFacilityRequestServersInner) Get() *CheckCapacityForFacilityRequestServersInner {
	return v.value
}

func (v *NullableCheckCapacityForFacilityRequestServersInner) Set(val *CheckCapacityForFacilityRequestServersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckCapacityForFacilityRequestServersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckCapacityForFacilityRequestServersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckCapacityForFacilityRequestServersInner(val *CheckCapacityForFacilityRequestServersInner) *NullableCheckCapacityForFacilityRequestServersInner {
	return &NullableCheckCapacityForFacilityRequestServersInner{value: val, isSet: true}
}

func (v NullableCheckCapacityForFacilityRequestServersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckCapacityForFacilityRequestServersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
