/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
)

// FindProjectAPIKeys200ResponseApiKeysInnerUser struct for FindProjectAPIKeys200ResponseApiKeysInnerUser
type FindProjectAPIKeys200ResponseApiKeysInnerUser struct {
	AvatarThumbUrl   *string                                `json:"avatar_thumb_url,omitempty"`
	AvatarUrl        *string                                `json:"avatar_url,omitempty"`
	CreatedAt        *time.Time                             `json:"created_at,omitempty"`
	Customdata       map[string]interface{}                 `json:"customdata,omitempty"`
	Email            *string                                `json:"email,omitempty"`
	Emails           []FindBatchById200ResponseDevicesInner `json:"emails,omitempty"`
	FirstName        *string                                `json:"first_name,omitempty"`
	FraudScore       *string                                `json:"fraud_score,omitempty"`
	FullName         *string                                `json:"full_name,omitempty"`
	Href             *string                                `json:"href,omitempty"`
	Id               *string                                `json:"id,omitempty"`
	LastLoginAt      *time.Time                             `json:"last_login_at,omitempty"`
	LastName         *string                                `json:"last_name,omitempty"`
	MaxOrganizations *int32                                 `json:"max_organizations,omitempty"`
	MaxProjects      *int32                                 `json:"max_projects,omitempty"`
	PhoneNumber      *string                                `json:"phone_number,omitempty"`
	ShortId          *string                                `json:"short_id,omitempty"`
	Timezone         *string                                `json:"timezone,omitempty"`
	TwoFactorAuth    *string                                `json:"two_factor_auth,omitempty"`
	UpdatedAt        *time.Time                             `json:"updated_at,omitempty"`
}

// NewFindProjectAPIKeys200ResponseApiKeysInnerUser instantiates a new FindProjectAPIKeys200ResponseApiKeysInnerUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindProjectAPIKeys200ResponseApiKeysInnerUser() *FindProjectAPIKeys200ResponseApiKeysInnerUser {
	this := FindProjectAPIKeys200ResponseApiKeysInnerUser{}
	return &this
}

// NewFindProjectAPIKeys200ResponseApiKeysInnerUserWithDefaults instantiates a new FindProjectAPIKeys200ResponseApiKeysInnerUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindProjectAPIKeys200ResponseApiKeysInnerUserWithDefaults() *FindProjectAPIKeys200ResponseApiKeysInnerUser {
	this := FindProjectAPIKeys200ResponseApiKeysInnerUser{}
	return &this
}

// GetAvatarThumbUrl returns the AvatarThumbUrl field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetAvatarThumbUrl() string {
	if o == nil || o.AvatarThumbUrl == nil {
		var ret string
		return ret
	}
	return *o.AvatarThumbUrl
}

// GetAvatarThumbUrlOk returns a tuple with the AvatarThumbUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetAvatarThumbUrlOk() (*string, bool) {
	if o == nil || o.AvatarThumbUrl == nil {
		return nil, false
	}
	return o.AvatarThumbUrl, true
}

// HasAvatarThumbUrl returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasAvatarThumbUrl() bool {
	if o != nil && o.AvatarThumbUrl != nil {
		return true
	}

	return false
}

// SetAvatarThumbUrl gets a reference to the given string and assigns it to the AvatarThumbUrl field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetAvatarThumbUrl(v string) {
	o.AvatarThumbUrl = &v
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetAvatarUrl() string {
	if o == nil || o.AvatarUrl == nil {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetAvatarUrlOk() (*string, bool) {
	if o == nil || o.AvatarUrl == nil {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasAvatarUrl() bool {
	if o != nil && o.AvatarUrl != nil {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCustomdata returns the Customdata field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetCustomdata() map[string]interface{} {
	if o == nil || o.Customdata == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Customdata
}

// GetCustomdataOk returns a tuple with the Customdata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetCustomdataOk() (map[string]interface{}, bool) {
	if o == nil || o.Customdata == nil {
		return nil, false
	}
	return o.Customdata, true
}

// HasCustomdata returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasCustomdata() bool {
	if o != nil && o.Customdata != nil {
		return true
	}

	return false
}

// SetCustomdata gets a reference to the given map[string]interface{} and assigns it to the Customdata field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetCustomdata(v map[string]interface{}) {
	o.Customdata = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetEmail(v string) {
	o.Email = &v
}

// GetEmails returns the Emails field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetEmails() []FindBatchById200ResponseDevicesInner {
	if o == nil || o.Emails == nil {
		var ret []FindBatchById200ResponseDevicesInner
		return ret
	}
	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetEmailsOk() ([]FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Emails == nil {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasEmails() bool {
	if o != nil && o.Emails != nil {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []FindBatchById200ResponseDevicesInner and assigns it to the Emails field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetEmails(v []FindBatchById200ResponseDevicesInner) {
	o.Emails = v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetFirstName() string {
	if o == nil || o.FirstName == nil {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetFirstNameOk() (*string, bool) {
	if o == nil || o.FirstName == nil {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasFirstName() bool {
	if o != nil && o.FirstName != nil {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetFirstName(v string) {
	o.FirstName = &v
}

// GetFraudScore returns the FraudScore field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetFraudScore() string {
	if o == nil || o.FraudScore == nil {
		var ret string
		return ret
	}
	return *o.FraudScore
}

// GetFraudScoreOk returns a tuple with the FraudScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetFraudScoreOk() (*string, bool) {
	if o == nil || o.FraudScore == nil {
		return nil, false
	}
	return o.FraudScore, true
}

// HasFraudScore returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasFraudScore() bool {
	if o != nil && o.FraudScore != nil {
		return true
	}

	return false
}

// SetFraudScore gets a reference to the given string and assigns it to the FraudScore field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetFraudScore(v string) {
	o.FraudScore = &v
}

// GetFullName returns the FullName field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetFullName() string {
	if o == nil || o.FullName == nil {
		var ret string
		return ret
	}
	return *o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetFullNameOk() (*string, bool) {
	if o == nil || o.FullName == nil {
		return nil, false
	}
	return o.FullName, true
}

// HasFullName returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasFullName() bool {
	if o != nil && o.FullName != nil {
		return true
	}

	return false
}

// SetFullName gets a reference to the given string and assigns it to the FullName field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetFullName(v string) {
	o.FullName = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetHref(v string) {
	o.Href = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetId(v string) {
	o.Id = &v
}

// GetLastLoginAt returns the LastLoginAt field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetLastLoginAt() time.Time {
	if o == nil || o.LastLoginAt == nil {
		var ret time.Time
		return ret
	}
	return *o.LastLoginAt
}

// GetLastLoginAtOk returns a tuple with the LastLoginAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetLastLoginAtOk() (*time.Time, bool) {
	if o == nil || o.LastLoginAt == nil {
		return nil, false
	}
	return o.LastLoginAt, true
}

// HasLastLoginAt returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasLastLoginAt() bool {
	if o != nil && o.LastLoginAt != nil {
		return true
	}

	return false
}

// SetLastLoginAt gets a reference to the given time.Time and assigns it to the LastLoginAt field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetLastLoginAt(v time.Time) {
	o.LastLoginAt = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetLastName() string {
	if o == nil || o.LastName == nil {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetLastNameOk() (*string, bool) {
	if o == nil || o.LastName == nil {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasLastName() bool {
	if o != nil && o.LastName != nil {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetLastName(v string) {
	o.LastName = &v
}

// GetMaxOrganizations returns the MaxOrganizations field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetMaxOrganizations() int32 {
	if o == nil || o.MaxOrganizations == nil {
		var ret int32
		return ret
	}
	return *o.MaxOrganizations
}

// GetMaxOrganizationsOk returns a tuple with the MaxOrganizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetMaxOrganizationsOk() (*int32, bool) {
	if o == nil || o.MaxOrganizations == nil {
		return nil, false
	}
	return o.MaxOrganizations, true
}

// HasMaxOrganizations returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasMaxOrganizations() bool {
	if o != nil && o.MaxOrganizations != nil {
		return true
	}

	return false
}

// SetMaxOrganizations gets a reference to the given int32 and assigns it to the MaxOrganizations field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetMaxOrganizations(v int32) {
	o.MaxOrganizations = &v
}

// GetMaxProjects returns the MaxProjects field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetMaxProjects() int32 {
	if o == nil || o.MaxProjects == nil {
		var ret int32
		return ret
	}
	return *o.MaxProjects
}

// GetMaxProjectsOk returns a tuple with the MaxProjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetMaxProjectsOk() (*int32, bool) {
	if o == nil || o.MaxProjects == nil {
		return nil, false
	}
	return o.MaxProjects, true
}

// HasMaxProjects returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasMaxProjects() bool {
	if o != nil && o.MaxProjects != nil {
		return true
	}

	return false
}

// SetMaxProjects gets a reference to the given int32 and assigns it to the MaxProjects field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetMaxProjects(v int32) {
	o.MaxProjects = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetPhoneNumberOk() (*string, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetShortId returns the ShortId field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetShortId() string {
	if o == nil || o.ShortId == nil {
		var ret string
		return ret
	}
	return *o.ShortId
}

// GetShortIdOk returns a tuple with the ShortId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetShortIdOk() (*string, bool) {
	if o == nil || o.ShortId == nil {
		return nil, false
	}
	return o.ShortId, true
}

// HasShortId returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasShortId() bool {
	if o != nil && o.ShortId != nil {
		return true
	}

	return false
}

// SetShortId gets a reference to the given string and assigns it to the ShortId field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetShortId(v string) {
	o.ShortId = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetTimezone() string {
	if o == nil || o.Timezone == nil {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetTimezoneOk() (*string, bool) {
	if o == nil || o.Timezone == nil {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasTimezone() bool {
	if o != nil && o.Timezone != nil {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetTimezone(v string) {
	o.Timezone = &v
}

// GetTwoFactorAuth returns the TwoFactorAuth field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetTwoFactorAuth() string {
	if o == nil || o.TwoFactorAuth == nil {
		var ret string
		return ret
	}
	return *o.TwoFactorAuth
}

// GetTwoFactorAuthOk returns a tuple with the TwoFactorAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetTwoFactorAuthOk() (*string, bool) {
	if o == nil || o.TwoFactorAuth == nil {
		return nil, false
	}
	return o.TwoFactorAuth, true
}

// HasTwoFactorAuth returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasTwoFactorAuth() bool {
	if o != nil && o.TwoFactorAuth != nil {
		return true
	}

	return false
}

// SetTwoFactorAuth gets a reference to the given string and assigns it to the TwoFactorAuth field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetTwoFactorAuth(v string) {
	o.TwoFactorAuth = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *FindProjectAPIKeys200ResponseApiKeysInnerUser) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o FindProjectAPIKeys200ResponseApiKeysInnerUser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AvatarThumbUrl != nil {
		toSerialize["avatar_thumb_url"] = o.AvatarThumbUrl
	}
	if o.AvatarUrl != nil {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Customdata != nil {
		toSerialize["customdata"] = o.Customdata
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.Emails != nil {
		toSerialize["emails"] = o.Emails
	}
	if o.FirstName != nil {
		toSerialize["first_name"] = o.FirstName
	}
	if o.FraudScore != nil {
		toSerialize["fraud_score"] = o.FraudScore
	}
	if o.FullName != nil {
		toSerialize["full_name"] = o.FullName
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.LastLoginAt != nil {
		toSerialize["last_login_at"] = o.LastLoginAt
	}
	if o.LastName != nil {
		toSerialize["last_name"] = o.LastName
	}
	if o.MaxOrganizations != nil {
		toSerialize["max_organizations"] = o.MaxOrganizations
	}
	if o.MaxProjects != nil {
		toSerialize["max_projects"] = o.MaxProjects
	}
	if o.PhoneNumber != nil {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if o.ShortId != nil {
		toSerialize["short_id"] = o.ShortId
	}
	if o.Timezone != nil {
		toSerialize["timezone"] = o.Timezone
	}
	if o.TwoFactorAuth != nil {
		toSerialize["two_factor_auth"] = o.TwoFactorAuth
	}
	if o.UpdatedAt != nil {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableFindProjectAPIKeys200ResponseApiKeysInnerUser struct {
	value *FindProjectAPIKeys200ResponseApiKeysInnerUser
	isSet bool
}

func (v NullableFindProjectAPIKeys200ResponseApiKeysInnerUser) Get() *FindProjectAPIKeys200ResponseApiKeysInnerUser {
	return v.value
}

func (v *NullableFindProjectAPIKeys200ResponseApiKeysInnerUser) Set(val *FindProjectAPIKeys200ResponseApiKeysInnerUser) {
	v.value = val
	v.isSet = true
}

func (v NullableFindProjectAPIKeys200ResponseApiKeysInnerUser) IsSet() bool {
	return v.isSet
}

func (v *NullableFindProjectAPIKeys200ResponseApiKeysInnerUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindProjectAPIKeys200ResponseApiKeysInnerUser(val *FindProjectAPIKeys200ResponseApiKeysInnerUser) *NullableFindProjectAPIKeys200ResponseApiKeysInnerUser {
	return &NullableFindProjectAPIKeys200ResponseApiKeysInnerUser{value: val, isSet: true}
}

func (v NullableFindProjectAPIKeys200ResponseApiKeysInnerUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindProjectAPIKeys200ResponseApiKeysInnerUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
