/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner struct for FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner
type FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner struct {
	Id     *string `json:"id,omitempty"`
	Native *bool   `json:"native,omitempty"`
	State  *string `json:"state,omitempty"`
	Vlan   *int32  `json:"vlan,omitempty"`
}

// NewFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner instantiates a new FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner() *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner {
	this := FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner{}
	return &this
}

// NewFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInnerWithDefaults instantiates a new FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInnerWithDefaults() *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner {
	this := FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) SetId(v string) {
	o.Id = &v
}

// GetNative returns the Native field value if set, zero value otherwise.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) GetNative() bool {
	if o == nil || o.Native == nil {
		var ret bool
		return ret
	}
	return *o.Native
}

// GetNativeOk returns a tuple with the Native field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) GetNativeOk() (*bool, bool) {
	if o == nil || o.Native == nil {
		return nil, false
	}
	return o.Native, true
}

// HasNative returns a boolean if a field has been set.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) HasNative() bool {
	if o != nil && o.Native != nil {
		return true
	}

	return false
}

// SetNative gets a reference to the given bool and assigns it to the Native field.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) SetNative(v bool) {
	o.Native = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) SetState(v string) {
	o.State = &v
}

// GetVlan returns the Vlan field value if set, zero value otherwise.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) GetVlan() int32 {
	if o == nil || o.Vlan == nil {
		var ret int32
		return ret
	}
	return *o.Vlan
}

// GetVlanOk returns a tuple with the Vlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) GetVlanOk() (*int32, bool) {
	if o == nil || o.Vlan == nil {
		return nil, false
	}
	return o.Vlan, true
}

// HasVlan returns a boolean if a field has been set.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) HasVlan() bool {
	if o != nil && o.Vlan != nil {
		return true
	}

	return false
}

// SetVlan gets a reference to the given int32 and assigns it to the Vlan field.
func (o *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) SetVlan(v int32) {
	o.Vlan = &v
}

func (o FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Native != nil {
		toSerialize["native"] = o.Native
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.Vlan != nil {
		toSerialize["vlan"] = o.Vlan
	}
	return json.Marshal(toSerialize)
}

type NullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner struct {
	value *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner
	isSet bool
}

func (v NullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) Get() *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner {
	return v.value
}

func (v *NullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) Set(val *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner(val *FindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) *NullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner {
	return &NullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner{value: val, isSet: true}
}

func (v NullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindPortVlanAssignmentBatches200ResponseBatchesInnerVlanAssignmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
