/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// FindDeviceEvents200ResponseMeta struct for FindDeviceEvents200ResponseMeta
type FindDeviceEvents200ResponseMeta struct {
	First    *FindBatchById200ResponseDevicesInner `json:"first,omitempty"`
	Last     *FindBatchById200ResponseDevicesInner `json:"last,omitempty"`
	Next     *FindBatchById200ResponseDevicesInner `json:"next,omitempty"`
	Previous *FindBatchById200ResponseDevicesInner `json:"previous,omitempty"`
	Self     *FindBatchById200ResponseDevicesInner `json:"self,omitempty"`
	Total    *int32                                `json:"total,omitempty"`
}

// NewFindDeviceEvents200ResponseMeta instantiates a new FindDeviceEvents200ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindDeviceEvents200ResponseMeta() *FindDeviceEvents200ResponseMeta {
	this := FindDeviceEvents200ResponseMeta{}
	return &this
}

// NewFindDeviceEvents200ResponseMetaWithDefaults instantiates a new FindDeviceEvents200ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindDeviceEvents200ResponseMetaWithDefaults() *FindDeviceEvents200ResponseMeta {
	this := FindDeviceEvents200ResponseMeta{}
	return &this
}

// GetFirst returns the First field value if set, zero value otherwise.
func (o *FindDeviceEvents200ResponseMeta) GetFirst() FindBatchById200ResponseDevicesInner {
	if o == nil || o.First == nil {
		var ret FindBatchById200ResponseDevicesInner
		return ret
	}
	return *o.First
}

// GetFirstOk returns a tuple with the First field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindDeviceEvents200ResponseMeta) GetFirstOk() (*FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.First == nil {
		return nil, false
	}
	return o.First, true
}

// HasFirst returns a boolean if a field has been set.
func (o *FindDeviceEvents200ResponseMeta) HasFirst() bool {
	if o != nil && o.First != nil {
		return true
	}

	return false
}

// SetFirst gets a reference to the given FindBatchById200ResponseDevicesInner and assigns it to the First field.
func (o *FindDeviceEvents200ResponseMeta) SetFirst(v FindBatchById200ResponseDevicesInner) {
	o.First = &v
}

// GetLast returns the Last field value if set, zero value otherwise.
func (o *FindDeviceEvents200ResponseMeta) GetLast() FindBatchById200ResponseDevicesInner {
	if o == nil || o.Last == nil {
		var ret FindBatchById200ResponseDevicesInner
		return ret
	}
	return *o.Last
}

// GetLastOk returns a tuple with the Last field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindDeviceEvents200ResponseMeta) GetLastOk() (*FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Last == nil {
		return nil, false
	}
	return o.Last, true
}

// HasLast returns a boolean if a field has been set.
func (o *FindDeviceEvents200ResponseMeta) HasLast() bool {
	if o != nil && o.Last != nil {
		return true
	}

	return false
}

// SetLast gets a reference to the given FindBatchById200ResponseDevicesInner and assigns it to the Last field.
func (o *FindDeviceEvents200ResponseMeta) SetLast(v FindBatchById200ResponseDevicesInner) {
	o.Last = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *FindDeviceEvents200ResponseMeta) GetNext() FindBatchById200ResponseDevicesInner {
	if o == nil || o.Next == nil {
		var ret FindBatchById200ResponseDevicesInner
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindDeviceEvents200ResponseMeta) GetNextOk() (*FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Next == nil {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *FindDeviceEvents200ResponseMeta) HasNext() bool {
	if o != nil && o.Next != nil {
		return true
	}

	return false
}

// SetNext gets a reference to the given FindBatchById200ResponseDevicesInner and assigns it to the Next field.
func (o *FindDeviceEvents200ResponseMeta) SetNext(v FindBatchById200ResponseDevicesInner) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *FindDeviceEvents200ResponseMeta) GetPrevious() FindBatchById200ResponseDevicesInner {
	if o == nil || o.Previous == nil {
		var ret FindBatchById200ResponseDevicesInner
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindDeviceEvents200ResponseMeta) GetPreviousOk() (*FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Previous == nil {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *FindDeviceEvents200ResponseMeta) HasPrevious() bool {
	if o != nil && o.Previous != nil {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given FindBatchById200ResponseDevicesInner and assigns it to the Previous field.
func (o *FindDeviceEvents200ResponseMeta) SetPrevious(v FindBatchById200ResponseDevicesInner) {
	o.Previous = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *FindDeviceEvents200ResponseMeta) GetSelf() FindBatchById200ResponseDevicesInner {
	if o == nil || o.Self == nil {
		var ret FindBatchById200ResponseDevicesInner
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindDeviceEvents200ResponseMeta) GetSelfOk() (*FindBatchById200ResponseDevicesInner, bool) {
	if o == nil || o.Self == nil {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *FindDeviceEvents200ResponseMeta) HasSelf() bool {
	if o != nil && o.Self != nil {
		return true
	}

	return false
}

// SetSelf gets a reference to the given FindBatchById200ResponseDevicesInner and assigns it to the Self field.
func (o *FindDeviceEvents200ResponseMeta) SetSelf(v FindBatchById200ResponseDevicesInner) {
	o.Self = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *FindDeviceEvents200ResponseMeta) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindDeviceEvents200ResponseMeta) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *FindDeviceEvents200ResponseMeta) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *FindDeviceEvents200ResponseMeta) SetTotal(v int32) {
	o.Total = &v
}

func (o FindDeviceEvents200ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.First != nil {
		toSerialize["first"] = o.First
	}
	if o.Last != nil {
		toSerialize["last"] = o.Last
	}
	if o.Next != nil {
		toSerialize["next"] = o.Next
	}
	if o.Previous != nil {
		toSerialize["previous"] = o.Previous
	}
	if o.Self != nil {
		toSerialize["self"] = o.Self
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableFindDeviceEvents200ResponseMeta struct {
	value *FindDeviceEvents200ResponseMeta
	isSet bool
}

func (v NullableFindDeviceEvents200ResponseMeta) Get() *FindDeviceEvents200ResponseMeta {
	return v.value
}

func (v *NullableFindDeviceEvents200ResponseMeta) Set(val *FindDeviceEvents200ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableFindDeviceEvents200ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableFindDeviceEvents200ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindDeviceEvents200ResponseMeta(val *FindDeviceEvents200ResponseMeta) *NullableFindDeviceEvents200ResponseMeta {
	return &NullableFindDeviceEvents200ResponseMeta{value: val, isSet: true}
}

func (v NullableFindDeviceEvents200ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindDeviceEvents200ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
