/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// SpotMarketPricesPerMetroList struct for SpotMarketPricesPerMetroList
type SpotMarketPricesPerMetroList struct {
	SpotMarketPrices *SpotMarketPricesPerMetroReport `json:"spot_market_prices,omitempty"`
}

// NewSpotMarketPricesPerMetroList instantiates a new SpotMarketPricesPerMetroList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpotMarketPricesPerMetroList() *SpotMarketPricesPerMetroList {
	this := SpotMarketPricesPerMetroList{}
	return &this
}

// NewSpotMarketPricesPerMetroListWithDefaults instantiates a new SpotMarketPricesPerMetroList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpotMarketPricesPerMetroListWithDefaults() *SpotMarketPricesPerMetroList {
	this := SpotMarketPricesPerMetroList{}
	return &this
}

// GetSpotMarketPrices returns the SpotMarketPrices field value if set, zero value otherwise.
func (o *SpotMarketPricesPerMetroList) GetSpotMarketPrices() SpotMarketPricesPerMetroReport {
	if o == nil || o.SpotMarketPrices == nil {
		var ret SpotMarketPricesPerMetroReport
		return ret
	}
	return *o.SpotMarketPrices
}

// GetSpotMarketPricesOk returns a tuple with the SpotMarketPrices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpotMarketPricesPerMetroList) GetSpotMarketPricesOk() (*SpotMarketPricesPerMetroReport, bool) {
	if o == nil || o.SpotMarketPrices == nil {
		return nil, false
	}
	return o.SpotMarketPrices, true
}

// HasSpotMarketPrices returns a boolean if a field has been set.
func (o *SpotMarketPricesPerMetroList) HasSpotMarketPrices() bool {
	if o != nil && o.SpotMarketPrices != nil {
		return true
	}

	return false
}

// SetSpotMarketPrices gets a reference to the given SpotMarketPricesPerMetroReport and assigns it to the SpotMarketPrices field.
func (o *SpotMarketPricesPerMetroList) SetSpotMarketPrices(v SpotMarketPricesPerMetroReport) {
	o.SpotMarketPrices = &v
}

func (o SpotMarketPricesPerMetroList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SpotMarketPrices != nil {
		toSerialize["spot_market_prices"] = o.SpotMarketPrices
	}
	return json.Marshal(toSerialize)
}

type NullableSpotMarketPricesPerMetroList struct {
	value *SpotMarketPricesPerMetroList
	isSet bool
}

func (v NullableSpotMarketPricesPerMetroList) Get() *SpotMarketPricesPerMetroList {
	return v.value
}

func (v *NullableSpotMarketPricesPerMetroList) Set(val *SpotMarketPricesPerMetroList) {
	v.value = val
	v.isSet = true
}

func (v NullableSpotMarketPricesPerMetroList) IsSet() bool {
	return v.isSet
}

func (v *NullableSpotMarketPricesPerMetroList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpotMarketPricesPerMetroList(val *SpotMarketPricesPerMetroList) *NullableSpotMarketPricesPerMetroList {
	return &NullableSpotMarketPricesPerMetroList{value: val, isSet: true}
}

func (v NullableSpotMarketPricesPerMetroList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpotMarketPricesPerMetroList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
