/*
Metal API

This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.

API version: 1.0.0
Contact: support@equinixmetal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// FindVrfIpReservations200Response struct for FindVrfIpReservations200Response
type FindVrfIpReservations200Response struct {
	IpAddresses []FindVrfIpReservations200ResponseIpAddressesInner `json:"ip_addresses,omitempty"`
}

// NewFindVrfIpReservations200Response instantiates a new FindVrfIpReservations200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindVrfIpReservations200Response() *FindVrfIpReservations200Response {
	this := FindVrfIpReservations200Response{}
	return &this
}

// NewFindVrfIpReservations200ResponseWithDefaults instantiates a new FindVrfIpReservations200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindVrfIpReservations200ResponseWithDefaults() *FindVrfIpReservations200Response {
	this := FindVrfIpReservations200Response{}
	return &this
}

// GetIpAddresses returns the IpAddresses field value if set, zero value otherwise.
func (o *FindVrfIpReservations200Response) GetIpAddresses() []FindVrfIpReservations200ResponseIpAddressesInner {
	if o == nil || o.IpAddresses == nil {
		var ret []FindVrfIpReservations200ResponseIpAddressesInner
		return ret
	}
	return o.IpAddresses
}

// GetIpAddressesOk returns a tuple with the IpAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindVrfIpReservations200Response) GetIpAddressesOk() ([]FindVrfIpReservations200ResponseIpAddressesInner, bool) {
	if o == nil || o.IpAddresses == nil {
		return nil, false
	}
	return o.IpAddresses, true
}

// HasIpAddresses returns a boolean if a field has been set.
func (o *FindVrfIpReservations200Response) HasIpAddresses() bool {
	if o != nil && o.IpAddresses != nil {
		return true
	}

	return false
}

// SetIpAddresses gets a reference to the given []FindVrfIpReservations200ResponseIpAddressesInner and assigns it to the IpAddresses field.
func (o *FindVrfIpReservations200Response) SetIpAddresses(v []FindVrfIpReservations200ResponseIpAddressesInner) {
	o.IpAddresses = v
}

func (o FindVrfIpReservations200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IpAddresses != nil {
		toSerialize["ip_addresses"] = o.IpAddresses
	}
	return json.Marshal(toSerialize)
}

type NullableFindVrfIpReservations200Response struct {
	value *FindVrfIpReservations200Response
	isSet bool
}

func (v NullableFindVrfIpReservations200Response) Get() *FindVrfIpReservations200Response {
	return v.value
}

func (v *NullableFindVrfIpReservations200Response) Set(val *FindVrfIpReservations200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFindVrfIpReservations200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFindVrfIpReservations200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindVrfIpReservations200Response(val *FindVrfIpReservations200Response) *NullableFindVrfIpReservations200Response {
	return &NullableFindVrfIpReservations200Response{value: val, isSet: true}
}

func (v NullableFindVrfIpReservations200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindVrfIpReservations200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
