// Code generated by go-swagger; DO NOT EDIT.

package capacity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/t0mk/gometal/types"
)

// NewCheckCapacityParams creates a new CheckCapacityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCheckCapacityParams() *CheckCapacityParams {
	return &CheckCapacityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCheckCapacityParamsWithTimeout creates a new CheckCapacityParams object
// with the ability to set a timeout on a request.
func NewCheckCapacityParamsWithTimeout(timeout time.Duration) *CheckCapacityParams {
	return &CheckCapacityParams{
		timeout: timeout,
	}
}

// NewCheckCapacityParamsWithContext creates a new CheckCapacityParams object
// with the ability to set a context for a request.
func NewCheckCapacityParamsWithContext(ctx context.Context) *CheckCapacityParams {
	return &CheckCapacityParams{
		Context: ctx,
	}
}

// NewCheckCapacityParamsWithHTTPClient creates a new CheckCapacityParams object
// with the ability to set a custom HTTPClient for a request.
func NewCheckCapacityParamsWithHTTPClient(client *http.Client) *CheckCapacityParams {
	return &CheckCapacityParams{
		HTTPClient: client,
	}
}

/* CheckCapacityParams contains all the parameters to send to the API endpoint
   for the check capacity operation.

   Typically these are written to a http.Request.
*/
type CheckCapacityParams struct {

	/* Facility.

	   Facility to create
	*/
	Facility *types.CapacityInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the check capacity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckCapacityParams) WithDefaults() *CheckCapacityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the check capacity params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckCapacityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the check capacity params
func (o *CheckCapacityParams) WithTimeout(timeout time.Duration) *CheckCapacityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check capacity params
func (o *CheckCapacityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check capacity params
func (o *CheckCapacityParams) WithContext(ctx context.Context) *CheckCapacityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check capacity params
func (o *CheckCapacityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check capacity params
func (o *CheckCapacityParams) WithHTTPClient(client *http.Client) *CheckCapacityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check capacity params
func (o *CheckCapacityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFacility adds the facility to the check capacity params
func (o *CheckCapacityParams) WithFacility(facility *types.CapacityInput) *CheckCapacityParams {
	o.SetFacility(facility)
	return o
}

// SetFacility adds the facility to the check capacity params
func (o *CheckCapacityParams) SetFacility(facility *types.CapacityInput) {
	o.Facility = facility
}

// WriteToRequest writes these params to a swagger request
func (o *CheckCapacityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Facility != nil {
		if err := r.SetBodyParam(o.Facility); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
