// Code generated by go-swagger; DO NOT EDIT.

package capacity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/t0mk/gometal/types"
)

// NewCheckCapacityForFacilityParams creates a new CheckCapacityForFacilityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCheckCapacityForFacilityParams() *CheckCapacityForFacilityParams {
	return &CheckCapacityForFacilityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCheckCapacityForFacilityParamsWithTimeout creates a new CheckCapacityForFacilityParams object
// with the ability to set a timeout on a request.
func NewCheckCapacityForFacilityParamsWithTimeout(timeout time.Duration) *CheckCapacityForFacilityParams {
	return &CheckCapacityForFacilityParams{
		timeout: timeout,
	}
}

// NewCheckCapacityForFacilityParamsWithContext creates a new CheckCapacityForFacilityParams object
// with the ability to set a context for a request.
func NewCheckCapacityForFacilityParamsWithContext(ctx context.Context) *CheckCapacityForFacilityParams {
	return &CheckCapacityForFacilityParams{
		Context: ctx,
	}
}

// NewCheckCapacityForFacilityParamsWithHTTPClient creates a new CheckCapacityForFacilityParams object
// with the ability to set a custom HTTPClient for a request.
func NewCheckCapacityForFacilityParamsWithHTTPClient(client *http.Client) *CheckCapacityForFacilityParams {
	return &CheckCapacityForFacilityParams{
		HTTPClient: client,
	}
}

/* CheckCapacityForFacilityParams contains all the parameters to send to the API endpoint
   for the check capacity for facility operation.

   Typically these are written to a http.Request.
*/
type CheckCapacityForFacilityParams struct {

	/* Facility.

	   Facility to check capacity in
	*/
	Facility *types.CapacityInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the check capacity for facility params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckCapacityForFacilityParams) WithDefaults() *CheckCapacityForFacilityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the check capacity for facility params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckCapacityForFacilityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the check capacity for facility params
func (o *CheckCapacityForFacilityParams) WithTimeout(timeout time.Duration) *CheckCapacityForFacilityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check capacity for facility params
func (o *CheckCapacityForFacilityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check capacity for facility params
func (o *CheckCapacityForFacilityParams) WithContext(ctx context.Context) *CheckCapacityForFacilityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check capacity for facility params
func (o *CheckCapacityForFacilityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check capacity for facility params
func (o *CheckCapacityForFacilityParams) WithHTTPClient(client *http.Client) *CheckCapacityForFacilityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check capacity for facility params
func (o *CheckCapacityForFacilityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFacility adds the facility to the check capacity for facility params
func (o *CheckCapacityForFacilityParams) WithFacility(facility *types.CapacityInput) *CheckCapacityForFacilityParams {
	o.SetFacility(facility)
	return o
}

// SetFacility adds the facility to the check capacity for facility params
func (o *CheckCapacityForFacilityParams) SetFacility(facility *types.CapacityInput) {
	o.Facility = facility
}

// WriteToRequest writes these params to a swagger request
func (o *CheckCapacityForFacilityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Facility != nil {
		if err := r.SetBodyParam(o.Facility); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
