// Code generated by go-swagger; DO NOT EDIT.

package otps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"os"
	"time"

	"github.com/go-openapi/strfmt"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func Command(ctx context.Context, client ClientService) *cobra.Command {
	command := cobra.Command{
		Use:   "otps",
		Short: "Client for otps",
	}

	command.AddCommand(findEnsureOtp(ctx, client))
	command.AddCommand(findRecoveryCodes(ctx, client))
	command.AddCommand(receiveCodes(ctx, client))
	command.AddCommand(regenerateCodes(ctx, client))

	return &command
}

func findEnsureOtp(ctx context.Context, client ClientService) *cobra.Command {
	parameters := &FindEnsureOtpParams{}

	command := &cobra.Command{
		Use: "FindEnsureOtp",
		RunE: func(cmd *cobra.Command, args []string) error {

			_, err := client.FindEnsureOtp(parameters, nil)
			return err

		},
	}

	parameters.Context = ctx

	// string

	command.PersistentFlags().StringVar(&parameters.Otp, "otp", "", "OTP")

	command.MarkPersistentFlagRequired("otp")

	return command
}

func findRecoveryCodes(ctx context.Context, client ClientService) *cobra.Command {
	parameters := &FindRecoveryCodesParams{}

	command := &cobra.Command{
		Use: "FindRecoveryCodes",
		RunE: func(cmd *cobra.Command, args []string) error {

			result, err := client.FindRecoveryCodes(parameters, nil)
			if err != nil {
				return err
			}
			return printPayload(result.Payload)

		},
	}

	parameters.Context = ctx

	return command
}

func receiveCodes(ctx context.Context, client ClientService) *cobra.Command {
	parameters := &ReceiveCodesParams{}

	command := &cobra.Command{
		Use: "ReceiveCodes",
		RunE: func(cmd *cobra.Command, args []string) error {

			_, err := client.ReceiveCodes(parameters, nil)
			return err

		},
	}

	parameters.Context = ctx

	return command
}

func regenerateCodes(ctx context.Context, client ClientService) *cobra.Command {
	parameters := &RegenerateCodesParams{}

	command := &cobra.Command{
		Use: "RegenerateCodes",
		RunE: func(cmd *cobra.Command, args []string) error {

			result, err := client.RegenerateCodes(parameters, nil)
			if err != nil {
				return err
			}
			return printPayload(result.Payload)

		},
	}

	parameters.Context = ctx

	return command
}

func printPayload(value interface{}) error {
	bytes, err := json.MarshalIndent(value, "", "  ")

	if err != nil {
		return err
	}

	_, err = os.Stdout.Write(bytes)
	return err
}

type dateTimeValue struct {
	v *strfmt.DateTime
}

func (dtv *dateTimeValue) String() string {
	return time.Time(*dtv.v).Format(strfmt.ISO8601LocalTime)
}

func (dtv *dateTimeValue) Set(flag string) error {
	return dtv.v.UnmarshalText([]byte(flag))
}

func (dtv *dateTimeValue) Type() string {
	return "dateTime"
}

func newDateTimeValue(v *strfmt.DateTime) pflag.Value {
	return &dateTimeValue{v}
}
