// Code generated by go-swagger; DO NOT EDIT.

package otps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewReceiveCodesParams creates a new ReceiveCodesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReceiveCodesParams() *ReceiveCodesParams {
	return &ReceiveCodesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReceiveCodesParamsWithTimeout creates a new ReceiveCodesParams object
// with the ability to set a timeout on a request.
func NewReceiveCodesParamsWithTimeout(timeout time.Duration) *ReceiveCodesParams {
	return &ReceiveCodesParams{
		timeout: timeout,
	}
}

// NewReceiveCodesParamsWithContext creates a new ReceiveCodesParams object
// with the ability to set a context for a request.
func NewReceiveCodesParamsWithContext(ctx context.Context) *ReceiveCodesParams {
	return &ReceiveCodesParams{
		Context: ctx,
	}
}

// NewReceiveCodesParamsWithHTTPClient creates a new ReceiveCodesParams object
// with the ability to set a custom HTTPClient for a request.
func NewReceiveCodesParamsWithHTTPClient(client *http.Client) *ReceiveCodesParams {
	return &ReceiveCodesParams{
		HTTPClient: client,
	}
}

/* ReceiveCodesParams contains all the parameters to send to the API endpoint
   for the receive codes operation.

   Typically these are written to a http.Request.
*/
type ReceiveCodesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the receive codes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReceiveCodesParams) WithDefaults() *ReceiveCodesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the receive codes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReceiveCodesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the receive codes params
func (o *ReceiveCodesParams) WithTimeout(timeout time.Duration) *ReceiveCodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the receive codes params
func (o *ReceiveCodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the receive codes params
func (o *ReceiveCodesParams) WithContext(ctx context.Context) *ReceiveCodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the receive codes params
func (o *ReceiveCodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the receive codes params
func (o *ReceiveCodesParams) WithHTTPClient(client *http.Client) *ReceiveCodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the receive codes params
func (o *ReceiveCodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ReceiveCodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
